#!/usr/bin/env python3
"""Rebuild the CONDITIONS data from the SRD 5.2.1 rules glossary — in BOTH tools.

The character sheet and Encounter Control must offer the same conditions, so one script writes
both. A test asserts the two lists agree; this is what makes that true by construction.

Idempotent: replaces the `const CONDITIONS=[...]` array where present, inserts it otherwise.
Touches only that array — the CSS and render code around it are ordinary source.

    python3 tools/build_conditions.py [srd-rules-glossary.md] [file.html ...]

SRD 5.2.1 Markdown (CC BY 4.0): https://github.com/downfallx/dnd-5e-srd-markdown
"""
import re, json, sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from srd_convert import convert

args     = sys.argv[1:]
GLOSSARY = args[0] if args else os.path.join(HERE, 'srd-rules-glossary.md')
TARGETS  = args[1:] or [os.path.join(HERE, '..', 'character-builder-2.html'),
                        os.path.join(HERE, '..', 'encounter-control.html')]

# Encounter Control's list carries two conditions the SRD does not define. They get no invented
# rules text — each points at the thing in this system that causes it.
HOMEBREW = [
    {'n': 'Concentrating',
     'd': '<p>You are sustaining a spell or ability that requires concentration. '
          'Its own description says what breaks it and what happens when it ends.</p>',
     'hb': 1},
    {'n': 'Raging',
     'd': '<p>You are in a rage. See the <em>Rage</em> talent for what it grants and what ends it.</p>',
     'hb': 1},
]

# Level-based rather than on/off: tracked by its own control in both tools, never as a chip.
LEVELLED = {'Exhaustion'}

NOTE = ("/* Conditions. Entries carrying a description reproduce the condition from the System\n"
        "   Reference Document 5.2.1, used under CC BY 4.0 — see legal.html. Changes were made: the\n"
        "   text was converted from Markdown to HTML; no wording was altered. Concentrating and\n"
        "   Raging are this system's own and carry no SRD text. Exhaustion is marked lvl:1 — it is\n"
        "   tracked by its own level control rather than as an on/off toggle.\n"
        "   Generated by tools/build_conditions.py — edit there, not here. */\n")

def main():
    text = open(GLOSSARY, encoding='utf-8').read()
    srd = []
    for chunk in re.split(r'^#### ', text, flags=re.M)[1:]:
        lines = chunk.split('\n')
        head = lines[0].strip()
        if not head.endswith('[Condition]'):
            continue
        name = head.replace('[Condition]', '').strip()
        _, body = convert('\n'.join(lines[1:]).strip())
        entry = {'n': name, 'd': body}
        if name in LEVELLED:
            entry['lvl'] = 1
        srd.append(entry)
    if not srd:
        sys.exit('no [Condition] entries found in %s' % GLOSSARY)

    conds = sorted(srd + HOMEBREW, key=lambda c: c['n'])
    data  = json.dumps(conds, ensure_ascii=False, separators=(',', ':'))
    block = 'const CONDITIONS=' + data + ';\n'

    for target in TARGETS:
        if not os.path.exists(target):
            print('skip (missing):', target); continue
        html = open(target, encoding='utf-8', newline='').read()
        m = re.search(r'const CONDITIONS\s*=\s*\[.*?\];\n?', html, re.S)
        if m:
            html = html[:m.start()] + block + html[m.end():]
        else:
            i = html.index('const SPELLS=') if 'const SPELLS=' in html else html.index('const S = ')
            html = html[:i] + NOTE + block + html[i:]
        open(target, 'w', encoding='utf-8', newline='').write(html)
        print('wrote %-28s %d conditions' % (os.path.basename(target), len(conds)))

    print('SRD %d · homebrew %d · level-based: %s · %.1f KB'
          % (len(srd), len(HOMEBREW), ', '.join(c['n'] for c in conds if c.get('lvl')), len(data)/1024))

if __name__ == '__main__':
    main()
