#!/usr/bin/env python3
"""Write the shared session-code codec into The Fray and the Character Builder.

The DM applies damage in `encounter-control.html`; the player's hit points live in
`character-builder-2.html`. Item 11 of `claude/PROJECT_REVIEW.md` is closing that gap, and since
the table plays remotely the two browsers can never talk to each other — so the carrier is a short
line of text the DM pastes into the group chat and the player pastes into their sheet.

Both tools therefore have to agree on that line **exactly**. Two hand-maintained copies of an
encoder and a decoder is the drift hazard this project has already paid for twice, so the codec is
generated into both files from here, byte-identical, and `test/session-code.test.js` asserts it.

    python3 tools/build_session_code.py            # write the block into both tools
    python3 tools/build_session_code.py --check    # verify, change nothing (exit 1 if stale)

Only the CODEC is shared. The user interface around it is hand-written in each tool, because the
two ends do opposite jobs: one copies, the other shows a diff and asks.

Insertion point is immediately before the navigation block (or the build stamp, or </body>), so
both generated blocks keep a stable order and the stamp still covers them.
"""
import re, sys, os

HERE_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT     = os.path.abspath(os.path.join(HERE_DIR, '..'))
PAGES    = ['encounter-control.html', 'character-builder-2.html']

OPEN  = '<!-- DYOP-SESSION start — generated by tools/build_session_code.py; do not edit by hand -->'
CLOSE = '<!-- DYOP-SESSION end -->'
BLOCK_RE = re.compile(re.escape(OPEN) + r'.*?' + re.escape(CLOSE) + r'\n?', re.S)
NAV_OPEN   = '<!-- DYOP-NAV start'
STAMP_OPEN = '<!-- build stamp — generated by tools/stamp_build.py; do not edit by hand -->'

JS = r"""<script>
/* Session codes — the line the DM pastes into chat and the player pastes into their sheet.
   Generated by tools/build_session_code.py. Edit that, not this.

       DYOP1|Kesh|hp:14/20|thp:0|tp:2/3|mana:6/12|exh:3|cond:Prone,Grappled|ts:2m9k1f|3f7q

   Design notes, because each choice is load-bearing:

   * It is ONE LINE of plain text. Chat clients wrap it but never alter it, and a player on a
     phone can paste it without a file dialog. A whole party is one line each; the decoder can
     pick a name out of a multi-line block, so the DM pastes once and every player pastes the
     same thing.
   * Names and condition text are percent-encoded, so no value can contain the field separators
     or smuggle markup through the line. `|` becomes %7C, `:` becomes %3A.
   * The trailing checksum catches a truncated copy or a stray character — the failure mode of
     pasting through chat — and turns it into "this code is damaged" rather than a wrong number
     silently applied.
   * Every value is ABSOLUTE, never a delta. Applying the same code twice is harmless, and a code
     that arrives out of order cannot compound.
   * `ts` is when the code was made. The receiving sheet uses it to warn that a code is older than
     one already applied; it is not a security measure and nothing depends on clocks agreeing.
   * Pools the character does not have (no mana, no talent points) are simply absent, and an
     absent field means "not sent" — never "set to zero".

   What this file does NOT decide: what the receiver does with the numbers. Maxima belong to the
   sheet, currents to the DM — see the apply path in character-builder-2.html. */
(function(){
  var VERSION = "DYOP1";
  var MAXLEN  = 400;                       /* a sane line; anything longer is not one of ours */

  function enc(s){ return encodeURIComponent(String(s == null ? "" : s)); }
  function dec(s){ try { return decodeURIComponent(String(s)); } catch (e) { return String(s); } }

  /* A small positional checksum in base 36. Not a hash and not a signature: it exists to catch a
     copy that lost characters on the way through a chat window. */
  function sum(s){
    var h = 0;
    for (var i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) % 1679616;   /* 36^4 */
    return ("000" + h.toString(36)).slice(-4);
  }

  function n0(v){ var n = Math.round(Number(v)); return isFinite(n) ? n : 0; }
  function pool(v){                          /* "14/20" -> {c:14, m:20}; anything else -> null */
    var m = /^(-?\d{1,6})\/(\d{1,6})$/.exec(String(v || ""));
    return m ? {c: +m[1], m: +m[2]} : null;
  }

  function encode(v, now){
    var p = [VERSION, enc(v && v.name)];
    if (v.hp   && v.hp.m   != null) p.push("hp:"   + n0(v.hp.c)   + "/" + n0(v.hp.m));
    if (v.thp  != null)             p.push("thp:"  + n0(v.thp));
    if (v.tp   && v.tp.m   > 0)     p.push("tp:"   + n0(v.tp.c)   + "/" + n0(v.tp.m));
    if (v.mana && v.mana.m > 0)     p.push("mana:" + n0(v.mana.c) + "/" + n0(v.mana.m));
    if (v.exh  != null)             p.push("exh:"  + n0(v.exh));
    p.push("cond:" + (v.cond || []).map(enc).join(","));
    p.push("ts:" + Math.floor((now == null ? Date.now() : now) / 1000).toString(36));
    var body = p.join("|");
    return body + "|" + sum(body);
  }

  function decode(line){
    var s = String(line == null ? "" : line).trim();
    if (!s) return {ok:false, err:"empty"};
    if (s.length > MAXLEN) return {ok:false, err:"too long to be a session code"};
    var p = s.split("|");
    if (p[0] !== VERSION) return {ok:false, err:"not a session code"};
    if (p.length < 4) return {ok:false, err:"incomplete code"};
    var given = p.pop();
    if (given !== sum(p.join("|"))) return {ok:false, err:"this code is damaged — copy it again"};

    var v = {name: dec(p[1]), cond: null, ts: null,
             hp: null, thp: null, tp: null, mana: null};
    if (!v.name) return {ok:false, err:"the code names no character"};

    for (var i = 2; i < p.length; i++){
      var at = p[i].indexOf(":");
      if (at < 0) return {ok:false, err:"malformed field in the code"};
      var k = p[i].slice(0, at), val = p[i].slice(at + 1);
      if (k === "hp" || k === "tp" || k === "mana"){
        var pl = pool(val);
        if (!pl) return {ok:false, err:"malformed " + k + " in the code"};
        v[k] = pl;
      } else if (k === "thp" || k === "exh"){
        if (!/^-?\d{1,6}$/.test(val)) return {ok:false, err:"malformed " + k + " in the code"};
        v[k] = +val;
      } else if (k === "cond"){
        v.cond = val === "" ? [] : val.split(",").map(dec);
      } else if (k === "ts"){
        v.ts = parseInt(val, 36) || null;
      }
      /* an unknown key is ignored on purpose, so a newer Fray can add a field without breaking
         an older sheet — the checksum still covers it */
    }
    return {ok:true, v:v};
  }

  /* Pull one character's line out of whatever was pasted: a single code, or the whole party's
     block. Returns the matching line, or the names that were on offer so the sheet can say
     "this update is for Brann, not you". */
  function pick(text, name){
    var lines = String(text == null ? "" : text).split(/[\r\n]+/), found = [], names = [], bad = null;
    for (var i = 0; i < lines.length; i++){
      var t = lines[i].trim();
      if (t.indexOf(VERSION) !== 0) continue;
      var r = decode(t);
      if (!r.ok){ bad = bad || r; continue; }
      found.push(r.v); names.push(r.v.name);
    }
    if (!found.length) return bad || {ok:false, err:"no session code found in that text", names:[]};
    var want = String(name == null ? "" : name).trim().toLowerCase();
    for (var j = 0; j < found.length; j++)
      if (found[j].name.trim().toLowerCase() === want) return {ok:true, v:found[j], names:names};
    return {ok:false, err:"that update is not for this character", names:names};
  }

  window.DYOP_SESSION = {VERSION:VERSION, encode:encode, decode:decode, pick:pick, sum:sum};
})();
</script>"""


def block():
    return '%s\n%s\n%s\n' % (OPEN, JS, CLOSE)


def process(path, check):
    page = os.path.basename(path)
    html = open(path, encoding='utf-8', newline='').read()
    want = block()
    have = BLOCK_RE.search(html)

    if check:
        if not have:              return (page, 'MISSING', False)
        if have.group(0) != want: return (page, 'STALE — regenerate', False)
        return (page, 'ok', True)

    body = BLOCK_RE.sub('', html)
    for marker in (NAV_OPEN, STAMP_OPEN):
        if marker in body:
            i = body.index(marker)
            break
    else:
        i = body.rindex('</body>')
    open(path, 'w', encoding='utf-8', newline='').write(body[:i] + want + body[i:])
    return (page, 'unchanged' if (have and have.group(0) == want) else
                  ('written' if not have else 'updated'), True)


def main():
    check   = '--check' in sys.argv
    args    = [a for a in sys.argv[1:] if not a.startswith('--')]
    targets = args or [os.path.join(ROOT, p) for p in PAGES]
    allok = True
    for t in targets:
        if not os.path.exists(t):
            print('  %-30s missing' % os.path.basename(t)); allok = False; continue
        page, msg, good = process(t, check)
        print('  %-30s %s' % (page, msg))
        allok = allok and good
    if check and not allok:
        print('\nThe session codec is stale or missing — run tools/build_session_code.py')
        sys.exit(1)


if __name__ == '__main__':
    main()
