#!/usr/bin/env python3
"""Write the campaign navigation menu into every published page.

Why a script and not five hand-edited copies: the menu names every tool on the site, so five
hand-maintained copies would be five chances to leave a renamed file behind — exactly the failure
HOSTING_AND_DEPLOYMENT.md §6 records ("a rename must reach GitHub and the hub in the same commit").
This keeps index.html as the ONE place links live: the campaign name, the base URL, the Drive
folder and the file names are read out of index.html's config block and compiled into the menu.

    python3 tools/build_nav.py            # write the block into every page
    python3 tools/build_nav.py --check    # verify, change nothing (exit 1 if stale or missing)

Idempotent: an existing block is removed before the new one is written, so re-running with no
config change rewrites the same bytes.

The emitted block is byte-identical in every page apart from one line — the `HERE` constant naming
the file it sits in, which is what marks "you are here" in the menu. test/nav.test.js asserts that.

Insertion point is immediately before the build stamp (or before </body> when a page has no stamp
yet), so tools/stamp_build.py keeps the last word and the stamp still covers the menu's bytes.
"""
import re, sys, os, json

HERE_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT     = os.path.abspath(os.path.join(HERE_DIR, '..'))

# index.html is deliberately absent: it IS the navigation, and a launcher there would be a button
# that opens a smaller copy of the page you are already looking at.
PAGES = ['character-builder-2.html', 'journal.html', 'compendium-and-bestiary.html',
         'encounter-control.html', 'dm-loom.html', 'legal.html']

OPEN  = '<!-- DYOP-NAV start — generated by tools/build_nav.py from index.html; do not edit by hand -->'
CLOSE = '<!-- DYOP-NAV end -->'
BLOCK_RE  = re.compile(re.escape(OPEN) + r'.*?' + re.escape(CLOSE) + r'\n?', re.S)
STAMP_OPEN = '<!-- build stamp — generated by tools/stamp_build.py; do not edit by hand -->'

# Which tools appear in the menu, in order, and which side of the screen they belong to.
# `dm: True` items are hidden from players — see the note about dyop_view in the generated JS.
TOOLS = [
    dict(key='builder',    dm=False, name='Character Builder',
         desc='Your sheet, levelling and play',
         ico='<path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>'),
    dict(key='journal',    dm=False, name='Adventure Journal',
         desc='Locations, NPCs, quests, memories',
         ico='<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/>'),
    dict(key='compendium', dm=False, name='Compendium &amp; Bestiary',
         desc='Rules, creatures and lore',
         ico='<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/><path d="M9 7h6M9 11h4"/>'),
    dict(key='encounter',  dm=True,  name='Encounter Control',
         desc='Initiative, damage, the combat record',
         ico='<circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/>'),
    dict(key='loom',       dm=True,  name='The Loom',
         desc='Worldbuilding forge and campaign codex',
         ico='<path d="M12 2l2.4 5.8L20 9l-4.5 4 1.3 6L12 16l-4.8 3 1.3-6L4 9l5.6-1.2L12 2Z"/>'),
]

CSS = """<style>
/* Campaign navigation — one launcher, one overlay. Everything is prefixed .dyop-nav so it cannot
   collide with a tool's own styles, and no custom property is read from the host page. */
.dyop-nav,.dyop-nav *{box-sizing:border-box}
.dyop-nav-fab{position:fixed; left:20px; bottom:20px; z-index:60; width:56px; height:56px;
  border-radius:50%; background:linear-gradient(145deg,#3f8f75,#2c6a58); color:#eafff6;
  border:1px solid #6cc0a1; padding:0; margin:0; cursor:pointer; font:inherit;
  box-shadow:0 6px 20px -6px #000c, 0 0 0 1px #0006;
  display:flex; align-items:center; justify-content:center; transition:transform .15s, box-shadow .15s}
.dyop-nav-fab:hover{transform:translateY(-2px); box-shadow:0 10px 26px -8px #000d, 0 0 18px -4px #3f8f75}
.dyop-nav-fab:active{transform:scale(.94)}
.dyop-nav-fab:focus-visible{outline:2px solid #ece6d6; outline-offset:3px}
.dyop-nav-fab svg{width:26px; height:26px; display:block}
/* Encounter Control pins a turn bar to the bottom during a fight; lift clear of it, the same way
   that tool already lifts its own dice button. Harmless on every page that has no .fighting. */
body.fighting .dyop-nav-fab{bottom:76px}

.dyop-nav-scrim{position:fixed; inset:0; z-index:500; background:#080a10c4; backdrop-filter:blur(3px);
  opacity:0; transition:opacity .16s}
.dyop-nav[data-open="true"] .dyop-nav-scrim{opacity:1}
.dyop-nav-panel{position:fixed; z-index:501; left:20px; bottom:88px; width:min(420px, calc(100vw - 40px));
  max-height:min(76vh, 640px); overflow:auto; background:#1b1e28; color:#d8d3c3;
  border:1px solid #303545; border-radius:16px; box-shadow:0 1px 0 #ffffff08, 0 24px 60px -20px #000e;
  font-family:"Spectral",Georgia,serif; font-size:16px; line-height:1.5; text-align:left;
  padding:16px; opacity:0; transform:translateY(8px) scale(.985); transition:opacity .16s, transform .16s}
.dyop-nav[data-open="true"] .dyop-nav-panel{opacity:1; transform:none}
.dyop-nav-panel:focus{outline:none}

.dyop-nav-head{display:flex; align-items:flex-start; gap:12px; padding:2px 2px 12px; border-bottom:1px solid #303545}
.dyop-nav-head .dyop-nav-htxt{flex:1; min-width:0}
.dyop-nav-title{font-family:"IM Fell English",Georgia,serif; font-size:1.15rem; color:#ece6d6; line-height:1.2}
.dyop-nav-camp{font-size:.68rem; color:#8a8fa0; text-transform:uppercase; letter-spacing:.12em; margin-top:5px}
.dyop-nav-x{background:transparent; border:1px solid #303545; color:#8a8fa0; border-radius:8px;
  width:30px; height:30px; flex:none; cursor:pointer; font:inherit; font-size:.85rem; line-height:1; padding:0}
.dyop-nav-x:hover{border-color:#3f8f75; color:#ece6d6}
.dyop-nav-x:focus-visible{outline:2px solid #6cc0a1; outline-offset:2px}

.dyop-nav-sec{font-size:.62rem; color:#8a8fa0; text-transform:uppercase; letter-spacing:.14em;
  margin:14px 2px 7px; font-family:"JetBrains Mono",ui-monospace,monospace}
.dyop-nav-item{display:flex; gap:11px; align-items:flex-start; padding:9px 10px; border-radius:10px;
  border:1px solid transparent; text-decoration:none; color:#d8d3c3; transition:.12s}
a.dyop-nav-item:hover{background:#232734; border-color:#3f8f75; color:#ece6d6}
a.dyop-nav-item:focus-visible{outline:2px solid #6cc0a1; outline-offset:1px}
.dyop-nav-item[aria-current="page"]{background:#232734; border-color:#303545; cursor:default}
.dyop-nav-item .dyop-nav-ico{width:19px; height:19px; flex:none; margin-top:2px; color:#6cc0a1}
.dyop-nav-item[aria-current="page"] .dyop-nav-ico{color:#d3b483}
.dyop-nav-nm{font-size:.94rem; color:#ece6d6; display:flex; align-items:baseline; gap:8px; flex-wrap:wrap}
.dyop-nav-item[aria-current="page"] .dyop-nav-nm{color:#d3b483}
.dyop-nav-ds{font-size:.76rem; color:#8a8fa0; margin-top:2px}
.dyop-nav-here{font-family:"JetBrains Mono",ui-monospace,monospace; font-size:.56rem; color:#14161f;
  background:#d3b483; border-radius:20px; padding:2px 7px; text-transform:uppercase; letter-spacing:.09em}

.dyop-nav-foot{display:flex; flex-wrap:wrap; gap:7px; margin-top:14px; padding-top:12px; border-top:1px solid #303545}
a.dyop-nav-chip{display:inline-flex; align-items:center; gap:6px; padding:6px 11px; border-radius:8px;
  border:1px solid #303545; background:#232734; color:#8a8fa0; text-decoration:none; font-size:.76rem; transition:.12s}
a.dyop-nav-chip:hover{border-color:#3f8f75; color:#ece6d6}
a.dyop-nav-chip:focus-visible{outline:2px solid #6cc0a1; outline-offset:1px}
a.dyop-nav-chip svg{width:13px; height:13px; flex:none}

@media(max-width:680px){
  .dyop-nav-fab{left:14px; bottom:14px; width:50px; height:50px}
  body.fighting .dyop-nav-fab{bottom:70px}
  .dyop-nav-panel{left:10px; right:10px; width:auto; bottom:76px; max-height:72vh}
}
@media(prefers-reduced-motion:reduce){
  .dyop-nav-fab,.dyop-nav-scrim,.dyop-nav-panel{transition:none}
  .dyop-nav-panel{transform:none}
}
@media print{.dyop-nav{display:none !important}}
</style>"""

JS = """<script>
/* Campaign navigation. Generated — edit tools/build_nav.py, not this block. */
(function(){
  if (window.__dyopNav) return;            /* never build twice */

  var HERE     = "@@HERE@@";
  var BASE     = "@@BASE@@";
  var CAMPAIGN = @@CAMPAIGN@@;
  var TOOLS    = @@TOOLS@@;
  var EXTRAS   = @@EXTRAS@@;

  /* The Player/DM switch on the portal writes this key. It is convenience, not secrecy — every
     file on the site is a public URL, as index.html says in as many words. Someone already inside
     a DM tool is obviously the DM, so the DM section shows there regardless of the saved view. */
  var dm = false;
  try { dm = localStorage.getItem("dyop_view") === "dm"; } catch (e) { dm = false; }
  for (var i = 0; i < TOOLS.length; i++) if (TOOLS[i].dm && TOOLS[i].file === HERE) dm = true;

  function el(tag, cls, text){
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
  }
  function svg(paths, cls){
    var s = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    s.setAttribute("viewBox", "0 0 24 24");
    s.setAttribute("fill", "none");
    s.setAttribute("stroke", "currentColor");
    s.setAttribute("stroke-width", "2");
    s.setAttribute("stroke-linecap", "round");
    s.setAttribute("stroke-linejoin", "round");
    s.setAttribute("aria-hidden", "true");
    if (cls) s.setAttribute("class", cls);
    s.innerHTML = paths;                   /* constants compiled into this file, never user text */
    return s;
  }

  var root  = el("div", "dyop-nav");
  root.setAttribute("data-open", "false");

  var fab = el("button", "dyop-nav-fab");
  fab.type = "button";
  fab.setAttribute("aria-label", "Campaign navigation");
  fab.setAttribute("aria-expanded", "false");
  fab.setAttribute("aria-haspopup", "dialog");
  fab.appendChild(svg('<circle cx="12" cy="12" r="10"/><path d="m16.2 7.8-2.4 6.6-6.6 2.4 2.4-6.6 6.6-2.4Z"/>'));

  var scrim = el("div", "dyop-nav-scrim");
  scrim.hidden = true;

  var panel = el("div", "dyop-nav-panel");
  panel.hidden = true;
  panel.tabIndex = -1;
  panel.setAttribute("role", "dialog");
  panel.setAttribute("aria-modal", "true");
  panel.setAttribute("aria-label", "Campaign navigation");

  var head = el("div", "dyop-nav-head");
  var htxt = el("div", "dyop-nav-htxt");
  htxt.appendChild(el("div", "dyop-nav-title", "Decide Your Own Path"));
  htxt.appendChild(el("div", "dyop-nav-camp", CAMPAIGN.name));
  head.appendChild(htxt);
  var x = el("button", "dyop-nav-x", "\\u2715");
  x.type = "button";
  x.setAttribute("aria-label", "Close navigation");
  head.appendChild(x);
  panel.appendChild(head);

  var list = el("nav", "dyop-nav-list");
  list.setAttribute("aria-label", "Campaign tools");
  panel.appendChild(list);

  function section(label){ list.appendChild(el("div", "dyop-nav-sec", label)); }

  function item(t){
    var here = (t.file === HERE);
    var n = el(here ? "div" : "a", "dyop-nav-item");
    if (here) { n.setAttribute("aria-current", "page"); }
    else      { n.href = BASE + t.file; }   /* same tab: every tool autosaves continuously */
    n.appendChild(svg(t.ico, "dyop-nav-ico"));
    var body = el("div");
    var nm   = el("div", "dyop-nav-nm");
    nm.appendChild(document.createTextNode(t.name));
    if (here) nm.appendChild(el("span", "dyop-nav-here", "you are here"));
    body.appendChild(nm);
    body.appendChild(el("div", "dyop-nav-ds", t.desc));
    n.appendChild(body);
    list.appendChild(n);
  }

  var players = [], dms = [];
  for (var j = 0; j < TOOLS.length; j++) (TOOLS[j].dm ? dms : players).push(TOOLS[j]);
  section("Your tools");
  players.forEach(item);
  if (dm) { section("DM tools"); dms.forEach(item); }

  var foot = el("div", "dyop-nav-foot");
  EXTRAS.forEach(function(e){
    if (!e.href) return;                                        /* no Drive folder configured */
    if (e.href.slice(-HERE.length) === HERE) return;            /* never link a page to itself */
    var a = el("a", "dyop-nav-chip");
    a.href = e.href;
    if (e.external) { a.target = "_blank"; a.rel = "noopener"; }
    a.appendChild(svg(e.ico));
    a.appendChild(document.createTextNode(e.label));
    foot.appendChild(a);
  });
  panel.appendChild(foot);

  root.appendChild(fab);
  root.appendChild(scrim);
  root.appendChild(panel);
  document.body.appendChild(root);

  var lastFocus = null;

  function focusables(){
    return panel.querySelectorAll('a[href], button:not([disabled])');
  }
  function open(){
    lastFocus = document.activeElement;
    scrim.hidden = false; panel.hidden = false;
    root.setAttribute("data-open", "true");
    fab.setAttribute("aria-expanded", "true");
    panel.focus();
    document.addEventListener("keydown", onKey, true);
  }
  function close(){
    root.setAttribute("data-open", "false");
    fab.setAttribute("aria-expanded", "false");
    scrim.hidden = true; panel.hidden = true;
    document.removeEventListener("keydown", onKey, true);
    /* Back where they came from — but a click does not focus a button everywhere (Safari), so an
       unfocused opener would strand focus on <body>. The launcher is the honest fallback. */
    var back = (lastFocus && lastFocus !== document.body && lastFocus.isConnected) ? lastFocus : fab;
    if (back && back.focus) back.focus();
  }
  function isOpen(){ return root.getAttribute("data-open") === "true"; }

  function onKey(ev){
    if (ev.key === "Escape") { ev.stopPropagation(); close(); return; }
    if (ev.key !== "Tab") return;
    var f = focusables();
    if (!f.length) { ev.preventDefault(); return; }
    var first = f[0], last = f[f.length - 1];
    if (ev.shiftKey && (document.activeElement === first || document.activeElement === panel)) {
      ev.preventDefault(); last.focus();
    } else if (!ev.shiftKey && document.activeElement === last) {
      ev.preventDefault(); first.focus();
    }
  }

  fab.addEventListener("click", function(){ isOpen() ? close() : open(); });
  x.addEventListener("click", close);
  scrim.addEventListener("click", close);

  window.__dyopNav = { open: open, close: close, isOpen: isOpen, here: HERE, dm: dm, root: root };
})();
</script>"""


def read_config():
    """The campaign name, the base URL, the Drive folder and the file names all live in
    index.html. Parsing them here is what stops this menu becoming a second place to edit."""
    html = open(os.path.join(ROOT, 'index.html'), encoding='utf-8').read()

    def one(pattern, what):
        m = re.search(pattern, html, re.S)
        if not m:
            sys.exit('index.html: could not find %s — has its config block moved?' % what)
        return m.group(1)

    base  = one(r'const\s+BASE\s*=\s*"([^"]+)"', 'the BASE constant')
    name  = one(r'const\s+CAMPAIGN\s*=\s*\{[^}]*?name:\s*"([^"]+)"', "CAMPAIGN.name")
    drive = re.search(r'driveFolder:\s*"([^"]*)"', html)
    files_src = one(r'const\s+FILES\s*=\s*\{(.*?)\}', 'the FILES map')
    files = dict(re.findall(r'(\w+)\s*:\s*"([^"]+)"', files_src))

    missing = [t['key'] for t in TOOLS if t['key'] not in files]
    if missing:
        sys.exit('index.html FILES is missing: %s' % ', '.join(missing))
    return dict(base=base, name=name, drive=(drive.group(1) if drive else ''), files=files)


def block_for(page, cfg):
    tools = [dict(key=t['key'], file=cfg['files'][t['key']], name=t['name'].replace('&amp;', '&'),
                  desc=t['desc'], dm=t['dm'], ico=t['ico']) for t in TOOLS]
    extras = [
        dict(label='Portal', href=cfg['base'] + 'index.html', external=False,
             ico='<path d="m3 10 9-7 9 7v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z"/><path d="M9 21v-8h6v8"/>'),
        dict(label='Shared folder', href=cfg['drive'], external=True,
             ico='<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/>'),
        dict(label='Licensing', href=cfg['base'] + 'legal.html', external=False,
             ico='<path d="M12 3v18"/><path d="M5 7h14"/><path d="m5 7-2 6a3 3 0 0 0 6 0Z"/><path d="m19 7 2 6a3 3 0 0 1-6 0Z"/>'),
    ]
    js = (JS.replace('@@HERE@@', page)
            .replace('@@BASE@@', cfg['base'])
            .replace('@@CAMPAIGN@@', json.dumps(dict(name=cfg['name'])))
            .replace('@@TOOLS@@', json.dumps(tools))
            .replace('@@EXTRAS@@', json.dumps(extras)))
    return '%s\n%s\n%s\n%s\n' % (OPEN, CSS, js, CLOSE)


def process(path, cfg, check):
    page = os.path.basename(path)
    html = open(path, encoding='utf-8', newline='').read()
    want = block_for(page, cfg)
    have = BLOCK_RE.search(html)

    if check:
        if not have:                       return (page, 'MISSING', False)
        if have.group(0) != want:          return (page, 'STALE — config changed since it was built', False)
        return (page, 'ok', True)

    body = BLOCK_RE.sub('', html)
    if STAMP_OPEN in body:
        i = body.index(STAMP_OPEN)         # keep the build stamp last
    else:
        i = body.rindex('</body>')
    open(path, 'w', encoding='utf-8', newline='').write(body[:i] + want + body[i:])
    return (page, 'unchanged' if (have and have.group(0) == want) else
                  ('written' if not have else 'updated'), True)


def main():
    check   = '--check' in sys.argv
    args    = [a for a in sys.argv[1:] if not a.startswith('--')]
    targets = args or [os.path.join(ROOT, p) for p in PAGES]
    cfg     = read_config()
    print('  config from index.html: %s · %s' % (cfg['name'], cfg['base']))
    allok = True
    for t in targets:
        if not os.path.exists(t):
            print('  %-30s missing' % os.path.basename(t)); allok = False; continue
        page, msg, good = process(t, cfg, check)
        print('  %-30s %s' % (page, msg))
        allok = allok and good
    if check and not allok:
        print('\nNavigation is stale or missing — run tools/build_nav.py'); sys.exit(1)


if __name__ == '__main__':
    main()
