#!/usr/bin/env python3
"""Stamp each published page with a build date and a content fingerprint.

Why a fingerprint and not just a date: two copies of a file edited on the same day look identical
by date. SECURITY_PATCHES.md §1 records a whole patch pass validating against the wrong copy
because there was no way to tell two versions apart. The `rev` here is a short SHA-1 of the file
with its own stamp removed, so it answers "is this the build I think it is?" directly.

    python3 tools/stamp_build.py                 # stamp every published page
    python3 tools/stamp_build.py --check         # verify stamps, change nothing (exit 1 if stale)
    python3 tools/stamp_build.py a.html b.html   # stamp specific files

Idempotent: the hash is computed over the content *without* the stamp, so re-running rewrites the
same bytes. The date only moves when the content actually changes — a rebuild that changes nothing
leaves the date alone.
"""
import re, sys, os, hashlib, datetime

HERE  = os.path.dirname(os.path.abspath(__file__))
ROOT  = os.path.abspath(os.path.join(HERE, '..'))
PAGES = ['index.html', 'character-builder-2.html', 'journal.html',
         'compendium-and-bestiary.html', 'encounter-control.html', 'dm-loom.html', 'legal.html']

OPEN  = '<!-- build stamp — generated by tools/stamp_build.py; do not edit by hand -->'
STYLE = ('<style>.dyop-build{max-width:1000px;margin:0 auto;padding:0 20px 26px;text-align:center;'
         'font-family:"JetBrains Mono",ui-monospace,monospace;font-size:.58rem;letter-spacing:.11em;'
         'text-transform:uppercase;color:#8a8fa0;opacity:.55}'
         '.dyop-build b{font-weight:400;color:#d3b483;opacity:.9}'
         '@media print{.dyop-build{display:none!important}}</style>')

STAMP_RE = re.compile(re.escape(OPEN) + r'.*?</div>\n?', re.S)

def strip(html):
    return STAMP_RE.sub('', html)

def rev_of(html):
    return hashlib.sha1(strip(html).encode('utf-8')).hexdigest()[:7]

def existing(html):
    m = re.search(r'<div class="dyop-build" data-build="([\d-]+)" data-rev="([0-9a-f]+)"', html)
    return (m.group(1), m.group(2)) if m else (None, None)

def block(name, date, rev):
    return ('%s\n%s\n<div class="dyop-build" data-build="%s" data-rev="%s">%s &middot; build %s '
            '&middot; <b>%s</b></div>\n' % (OPEN, STYLE, date, rev, name, date, rev))

def process(path, check):
    name = os.path.basename(path)
    html = open(path, encoding='utf-8', newline='').read()
    rev  = rev_of(html)
    old_date, old_rev = existing(html)

    if check:
        if old_rev is None:      return (name, 'NOT STAMPED', False)
        if old_rev != rev:       return (name, 'STALE — content changed since %s (%s -> %s)'
                                                % (old_date, old_rev, rev), False)
        return (name, 'ok  %s  %s' % (old_date, old_rev), True)

    # the date only moves when the content actually moved
    date = old_date if (old_rev == rev and old_date) else datetime.date.today().isoformat()
    body = strip(html)
    i = body.rindex('</body>')
    open(path, 'w', encoding='utf-8', newline='').write(body[:i] + block(name, date, rev) + body[i:])
    state = 'unchanged' if old_rev == rev else ('stamped' if old_rev is None else 'updated')
    return (name, '%-9s %s  %s' % (state, date, rev), True)

def main():
    args   = [a for a in sys.argv[1:] if not a.startswith('--')]
    check  = '--check' in sys.argv
    targets = args or [os.path.join(ROOT, p) for p in PAGES]
    allok = True
    for t in targets:
        if not os.path.exists(t):
            print('  %-30s missing' % os.path.basename(t)); allok = False; continue
        name, msg, good = process(t, check)
        print('  %-30s %s' % (name, msg))
        allok = allok and good
    if check and not allok:
        print('\nStamps are stale or missing — run tools/stamp_build.py'); sys.exit(1)

if __name__ == '__main__':
    main()
